replicaCount: 2

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

image:
  #name: ghcr.io/octarect/hostname
  name: nginx:1.11
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: gitlab-registry

nameOverride: "myapp"
fullnameOverride: "myapp"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

env: []

vault:
  enabled: false

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: myapp.example.com
      paths:
        - /
  tls: []

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 0.2
    memory: 256Mi

extraVolumeMounts:
  - name: timezone
    mountPath: /etc/localtime
    readOnly: true

extraVolumes:
  - name: timezone
    hostPath:
      path: /usr/share/zoneinfo/Asia/Aqtobe
      type: ""

livenessProbe: []
readinessProbe: []
nodeSelector: []
tolerations: []
affinity: {}
