include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

variables:
  DOCKER_BUILD_ARG: '' # Define in mail yaml like "--build-arg CI_COMMIT_TAG --build-arg CI_COMMIT_SHA"
  REGISTRY: 'git-registry.egs.kz'
  IMAGE_NAME: "$REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"

stages:
  - pre-build
  - containerize
  - test
  - post-build

secret_detection:
  stage: pre-build
  allow_failure: true

docker-image:
  stage: containerize
  image: docker:19.03
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build ${DOCKER_BUILD_ARG} -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
    - docker rmi ${IMAGE_NAME}

container_scanning:
  variables:
    CS_IMAGE: "$IMAGE_NAME"
  stage: post-build

unit-tests:
  image: ubuntu:22.04
  stage: test
  tags:
    - docker
  script:
    - echo "running Unit tests ..."
