variables:
  DOCKER_BUILD_ARG: '' # Define in mail yaml like "--build-arg CI_COMMIT_TAG --build-arg CI_COMMIT_SHA"
  REGISTRY: 'git-registry.egs.kz'
  IMAGE_NAME: "$REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"

stages:
  - containerize
  - test

docker-image:
  stage: containerize
  image: docker:19.03
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo "${IMAGE_NAME}"
    - docker build ${DOCKER_BUILD_ARG} -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
    - docker rmi ${IMAGE_NAME}

unit-tests:
  stage: test
  image: docker:19.03
  tags:
    - docker
  script:
    - echo "running unit tests"
